# Generated by Django 4.0.4 on 2022-04-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
